import Navbar from './navbar';
import { font__default } from '../utils/fonts.js';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<div className={font__default.className + ` container mx-auto px-8`}>{children}</div>
			</body>
		</html>
	);
}

