import Navbar from './navbar';
import { font__default, font__accent, font__display, font__fancy } from '../utils/fonts.js';
import './globals.css';
import HeadingClassApplier from '../components/HeadingClassApplier'; // Import the client component

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${font__default.variable} ${font__accent.variable} ${font__display.variable} ${font__fancy.variable}`}>
			<body>
				<Navbar />
				<div className={`container mx-auto px-8 max-w-6xl`}>{children}</div>
				<HeadingClassApplier />
				
				<footer className="p-8">
					<div className="flex container">
						<div className="column">
							<h4>Explore</h4>
						</div>
						<div className="column">
							<h4>Explore</h4>
						</div>
					</div>
				</footer>
			</body>
		</html>
	);
}

