import Navbar from './navbar';
import { font__default, font__accent, font__display } from '../utils/fonts.js';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${font__default.variable} ${font__accent.variable} ${font__display.variable}`}>
			<body>
				<Navbar />
				<div className={`container mx-auto px-8`}>{children}</div>
			</body>
		</html>
	);
}

